### ISSUE TITLE
Chaos Monkey inspec test not working

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-aws-stack-provisioner#106]
The Chaos Monkey inspec test is currently not working. 

There are two reasons why it's not working:

1. The Path to the hiera file in the spec_helper.rb is not correct
2. The current ruby hiera library does not support hiera version 5

**Comment by mbloch1986** [comment]
Additional information regarding point 2:

https://github.com/puppetlabs/hiera/blob/master/lib/hiera/config.rb#L31

**Comment by cliffano** [comment]
Done. Fixed in v3.2.0 .
