### ISSUE TITLE
systemd - intermittent failure to stop awslogs correctly on publish instances

### ISSUE THREAD

**Issue by engshine** [shinesolutions/aem-aws-stack-provisioner#169]
An intermittent issue on publish instances where awslogs fails to stop and returns an error code of 1 that stops the rest of the puppet manifest.

The steps in the manifest are:
  systemctl disable ${$awslogs_service_name}
  systemctl stop ${$awslogs_service_name}

When the issue occurs, the systemctl command outputs:
  Job for awslogs.service canceled
with an error code of 1.

Hence puppet exits and the rest of the stack-init.sh does not execute correctly (as the snapshot is never attached).

**Comment by engshine** [comment]
The fix is with this commit: [https://github.com/shinesolutions/aem-aws-stack-provisioner/pull/170/commits/a9c958bab317ddb0d7472eee2ed5f964e403c692](url)

**Comment by cliffano** [comment]
Done. Included in version 4.1.0 .
