### ISSUE TITLE
CRON jobs fail when proxies are required

### ISSUE THREAD

**Issue by engshine** [shinesolutions/aem-aws-stack-provisioner#171]
The cron job:
/opt/shinesolutions/aem-tools/stack-offline-snapshot.sh

failed the inspec test (checking if a snapshot exists) as api requests to AWS was blocked due to missing proxy.

The manifest that add to the cron job only contains the environment variables:
PATH and https_proxy.

The issue is resolved when we set http_proxy.

**Comment by mbloch1986** [comment]
Fixed with version 4.3.0
