### ISSUE TITLE
wait_for_ec2tags.py - retries need to be user configurable

### ISSUE THREAD

**Issue by engshine** [shinesolutions/aem-aws-stack-provisioner#176]
The max_retries and delay variables in that script need to be user configurable.
The change to publish/dispatcher where the second, third, forth etc publish/dispatcher pairs wait for the initial publish/dispatcher pair to complete means that the retry limit gets breached causing the Jenkins job to fail when doing the readiness check.

The stack continues to get provisioned successfully, but as the pipeline has failed, the user is expected to discard this stack.

As each site have different requirements, these configuration items need to be configurable so that the timings can all be worked out.

**Comment by mbloch1986** [comment]
wait_for_ec2tags retries is extended to 4h which should be sufficient enough.
