### ISSUE TITLE
AEM author publish timeout when attaching snapshot needs to be configurable

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-provisioner#177]
The current 15 seconds timeout is not suitable for all types of repositories, this needs to be configurable as each user would have a different setting.

**Comment by mbloch1986** [comment]
We removed the puppet execution time out and are now relying on the timeout of the python scripts which are set to 4h since [4.29.0](https://github.com/shinesolutions/aem-aws-stack-provisioner/blob/master/CHANGELOG.md#4290---2020-03-01)
