### ISSUE TITLE
Wrong file name for AWS default region

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-aws-stack-provisioner#205]
The name of the file we are creating to configure the default aws region is wrong.

We are creating the file `~/.aws/credentials` with the content: 

[default]
region=<%= $region %>

The file name `~/.aws/credentials` is as the name suggest used for credentials, therefore the AWS-SDK is assuming that the credentials are locally configured for the user and any interaction to the aws-sdk may fail as the aws_access_key_id & aws_secret_access_key are not defined in the credentials file. E.g. The ruby aws-sdk client will fail because it assumes the default profile in the credentials file is used to establish the API Client and will fail because no credentials are defined.

To fix this we have to rename the file `~/.aws/credentials` to `~/.aws/config`.

**Comment by cliffano** [comment]
For future reference: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

**Comment by cliffano** [comment]
Done. Included in release 3.8.0 .
