### ISSUE TITLE
setting collectd cloudwatch proxy bug

### ISSUE THREAD

**Issue by michaeldiender-shinesolutions** [shinesolutions/aem-aws-stack-provisioner#28]
if you are not using an internet proxy. the puppet manifest will modify the plugin.conf file, but will cause the collectd cloudwatch not to work.

https://github.com/shinesolutions/aem-aws-stack-provisioner/blob/master/manifests/author-standby.pp#L27

and 

https://github.com/shinesolutions/aem-aws-stack-provisioner/blob/master/manifests/author-standby.pp#L34

**Comment by mbloch1986** [comment]
Configuration is now in 

https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#116

https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_standby.pp#L74
