### ISSUE TITLE
Upgrade hiera.yaml from version 3 to 5

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-provisioner#3]
Need to clean up the warning below:
Warning: /opt/shinesolutions/aem-aws-stack-provisioner/conf/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5

**Comment by mbloch1986** [comment]
The migration steps are described here:
https://puppet.com/docs/puppet/4.10/hiera_migrate_v3_yaml.html

The Version 5  of the hiera configuraiton doesn't support configuration parameters to define the merge  behavior. This is now set At lookup time or in the hiera data. 

For more information :
https://puppet.com/docs/puppet/5.4/hiera_merging.html

**Comment by mbloch1986** [comment]
Introduced in AEM AWS STack Provisioner version 2.5.0
