### ISSUE TITLE
Orchestrator logs into CloudWatch Logs

### ISSUE THREAD

**Issue by irgeek** [shinesolutions/aem-aws-stack-provisioner#35]
The orchestrator logs should be streamed into CloudWatch Logs with other logs.

**Comment by ovlords** [comment]
Added in commit: a52f55c

**Comment by irgeek** [comment]
@ovlords The commit you mentioned doesn't exist in this repo.

**Comment by ovlords** [comment]
This issue was addressed in the merge request.
