### ISSUE TITLE
Deploy on init feature

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-provisioner#45]
Introduce a new flag `enable_deploy_on_init` , which will execute package (AEM and dispatcher config) as part of stack initialisation.

When it's enabled, execute package AEM package deployment on author and publish, and the config on dispatcher.

**Comment by ovlords** [comment]
Created a stub

**Comment by cliffano** [comment]
Done. Will be included in stack builder 2.1.0 .
