### ISSUE TITLE
Enable JMXRemote for AEM to enable monitoring of the Java process via cloudwatch

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-aws-stack-provisioner#51]
In order to get collectd send metrics from the running AEM Java instance to AWS Cloudwatch jmx needs to be enable.

Furthermore it makes sense to make the port configurable in the configuration file.

**Comment by cliffano** [comment]
Done.
Included in aem_curator 0.9.10, which is included in stack-provisioner 2.4.0 and stack-builder 2.1.0 .
