### ISSUE TITLE
AuthorPublishDispatcher snapshot tags does not distinguish Author/Publish types

### ISSUE THREAD

**Issue by ovlords** [shinesolutions/aem-aws-stack-provisioner#58]
When running either of the snapshot scripts (see below) for AuthorPublishDispatcher:

templates/aem-tools/live-snapshot-backup.sh.epp
templates/aem-tools/offline-snapshot-backup.sh.epp

They will create 2 snapshot volumes in AWS (one for Author (sdb) and one for Publisher (sbc)), there is currently no way to tell which one is for Author or Publisher.

We need another tag to indicate if it was for Author or Publisher.

Possibly require introducing a new variable in: aem-aws-stack-provisioner/data/author-publish-dispatcher.yaml 

author_publish_dispatcher::aem_repo_devices:
  - /dev/sdb
  - /dev/sdc

**Comment by cliffano** [comment]
Done. Included in v2.4.3 .
