### ISSUE TITLE
Snapshot attachment should remove original volume

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-provisioner#59]
When a new snapshot is specified as part of starting an AEM Author or Publish instance, the original (detached) volume still lies around after the new volume is attached. This will pile up and unnecessarily waste resources, and with a large number of environments, it could easily cause the account to hit the soft limit.

The original volume should be detached after the new volume is successfully attached and the device mounted. https://github.com/shinesolutions/aem-aws-stack-provisioner/blob/master/files/aws-tools/snapshot_attach.py#L468

**Comment by zsustar** [comment]
add following: https://github.com/shinesolutions/aem-aws-stack-provisioner/blob/master/files/aws-tools/snapshot_attach.py#315
            #remove original volume
            current_volume.delete()
            log.info('Current volume will be deleted ')

**Comment by cliffano** [comment]
Done. To be included in 2.4.16 .
